/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
__export(exports, {
  default: () => PDFAnnotationPlugin
});
var import_obsidian = __toModule(require("obsidian"));
function template(strings, ...keys) {
  return function(...values) {
    const dict = values[values.length - 1] || {};
    const result = [strings[0]];
    keys.forEach(function(key, i) {
      const value = Number.isInteger(key) ? values[key] : dict[key];
      result.push(value, strings[i + 1]);
    });
    return result.join("");
  };
}
var highlighted = template`> ${"highlightedText"}

${"body"}
			    
* *highlighted by ${"author"} at page ${"pageNumber"} on [[${"filepath"}]]*

`;
var note = template`${"body"}
  
* *noted by ${"author"} at page ${"pageNumber"} on [[${"filepath"}]]*

`;
var SUPPORTED_ANNOTS = ["Text", "Highlight", "Underline"];
var PDFAnnotationPlugin = class extends import_obsidian.Plugin {
  loadPage(page, pagenum, file, containingFolder, editor, total) {
    return __async(this, null, function* () {
      const settings = this.settings;
      let annotations = yield page.getAnnotations();
      annotations = annotations.filter(function(anno) {
        return SUPPORTED_ANNOTS.indexOf(anno.subtype) >= 0;
      });
      if (annotations.length > 0 && editor != null) {
        editor.replaceSelection("PDF Page " + pagenum + " on " + file.name + " has " + annotations.length + " Annots.\n");
      }
      console.log("PDF Page " + pagenum + " on " + file.name + " has " + annotations.length + " Annots");
      const content = yield page.getTextContent({ normalizeWhitespace: true });
      content.items.sort(function(a1, a2) {
        if (a1.transform[5] > a2.transform[5])
          return -1;
        if (a1.transform[5] < a2.transform[5])
          return 1;
        if (a1.transform[4] > a2.transform[4])
          return 1;
        if (a1.transform[4] < a2.transform[4])
          return -1;
        return 0;
      });
      annotations.map(function(anno) {
        return __async(this, null, function* () {
          if (anno.subtype == "Highlight" || anno.subtype == "Underline") {
            const minx = anno.rect[0] < anno.rect[2] ? anno.rect[0] : anno.rect[2];
            const maxx = anno.rect[0] < anno.rect[2] ? anno.rect[2] : anno.rect[0];
            const miny = anno.rect[1] < anno.rect[3] ? anno.rect[1] : anno.rect[3];
            const maxy = anno.rect[1] < anno.rect[3] ? anno.rect[3] : anno.rect[1];
            const mycontent = content.items.filter(function(x) {
              if (x.width == 0)
                return false;
              if (!(miny <= x.transform[5] && x.transform[5] <= maxy))
                return false;
              if (minx <= x.transform[4] && x.transform[4] <= maxx)
                return true;
              if (x.transform[4] <= minx && x.transform[4] + x.width >= minx)
                return false;
            });
            let r = "???";
            if (mycontent.length > 0) {
              r = "";
              let y = mycontent[0].transform[5];
              mycontent.forEach((textContent) => {
                if (textContent.transform[5] != y) {
                  y = textContent.transform[5];
                  if (r.endsWith("-")) {
                    r = r.slice(0, -1) + textContent.str;
                  } else {
                    r += " " + textContent.str;
                  }
                } else {
                  r += textContent.str;
                }
              });
            } else {
              console.warn("No highlighted text found.");
              console.log(`${file.name} (Page ${pagenum}) rect ${minx} < x < ${maxx}, ${miny} < y < ${maxy}`);
              console.log("content", content);
            }
            anno.highlightedText = r;
          }
          const lines = anno.contentsObj.str.split(/\r\n|\n\r|\n|\r/);
          anno.topic = lines[0];
          if (settings.sortByTopic) {
            anno.body = lines.slice(1).join("\r\n");
          } else {
            anno.body = anno.contentsObj.str;
          }
          anno.folder = containingFolder;
          anno.file = file;
          anno.filepath = file.path;
          anno.pageNumber = pagenum;
          anno.author = anno.titleObj.str;
          total.push(anno);
        });
      });
    });
  }
  loadPDFFile(file, pdfjsLib, containingFolder, total, editor) {
    return __async(this, null, function* () {
      const content = yield this.app.vault.readBinary(file);
      const pdf = yield pdfjsLib.getDocument(content).promise;
      for (let i = 1; i <= pdf.numPages; i++) {
        const page = yield pdf.getPage(i);
        yield this.loadPage(page, i, file, containingFolder, editor, total);
      }
    });
  }
  sort(grandtotal) {
    const settings = this.settings;
    grandtotal.sort(function(a1, a2) {
      if (settings.sortByTopic) {
        if (a1.topic > a2.topic)
          return 1;
        if (a1.topic < a2.topic)
          return -1;
      }
      if (settings.useFolderNames) {
        if (a1.folder > a2.folder)
          return 1;
        if (a1.folder < a2.folder)
          return -1;
      }
      if (a1.file.name > a2.file.name)
        return 1;
      if (a1.file.name < a2.file.name)
        return -1;
      if (a1.pageNumber > a2.pageNumber)
        return 1;
      if (a1.pageNumber < a2.pageNumber)
        return -1;
      if (a1.rect[1] > a2.rect[1])
        return -1;
      if (a1.rect[1] < a2.rect[1])
        return 1;
      return 0;
    });
  }
  format(grandtotal) {
    let text = "";
    let topic = "";
    let currentFolder = "";
    const settings = this.settings;
    grandtotal.forEach((a) => {
      if (settings.sortByTopic) {
        if (topic != a.topic) {
          topic = a.topic;
          currentFolder = "";
          text += `# ${topic}
`;
        }
      }
      if (settings.useFolderNames) {
        if (currentFolder != a.folder) {
          currentFolder = a.folder;
          text += `## ${currentFolder}
`;
        }
      } else {
        if (currentFolder != a.file.name) {
          currentFolder = a.file.name;
          text += `## ${currentFolder}
`;
        }
      }
      if (a.subtype == "Text") {
        text += note(a);
      } else {
        text += highlighted(a);
      }
    });
    if (grandtotal.length == 0)
      return "*No Annotations*";
    else
      return text;
  }
  loadSinglePDFFile(file) {
    return __async(this, null, function* () {
      const pdfjsLib = yield (0, import_obsidian.loadPdfJs)();
      const containingFolder = file.parent.name;
      const grandtotal = [];
      console.log("loading from file ", file);
      yield this.loadPDFFile(file, pdfjsLib, containingFolder, grandtotal, null);
      this.sort(grandtotal);
      const finalMarkdown = this.format(grandtotal);
      let filePath = file.name.replace(".pdf", ".md");
      filePath = "Annotations for " + filePath;
      yield this.saveHighlightsToFile(filePath, finalMarkdown);
      yield this.app.workspace.openLinkText(filePath, "", true);
    });
  }
  onload() {
    return __async(this, null, function* () {
      this.loadSettings();
      this.addSettingTab(new PDFAnnotationPluginSettingTab(this.app, this));
      this.addCommand({
        id: "extract-annotations-single",
        name: "Extract PDF Annotations on single file",
        checkCallback: (checking) => {
          const file = this.app.workspace.getActiveFile();
          if (file != null && file.extension === "pdf") {
            if (!checking) {
              this.loadSinglePDFFile(file);
            }
            return true;
          } else {
            return false;
          }
        }
      });
      this.addCommand({
        id: "extract-annotations",
        name: "Extract PDF Annotations",
        editorCallback: (editor, view) => __async(this, null, function* () {
          const file = this.app.workspace.getActiveFile();
          if (file == null)
            return;
          const folder = file.parent;
          const grandtotal = [];
          const pdfjsLib = yield (0, import_obsidian.loadPdfJs)();
          editor.replaceSelection("Extracting PDF Comments from " + folder.name + "\n");
          const promises = [];
          import_obsidian.Vault.recurseChildren(folder, (file2) => __async(this, null, function* () {
            if (file2 instanceof import_obsidian.TFile) {
              if (file2.extension === "pdf") {
                const containingFolder = file2.parent.name;
                promises.push(this.loadPDFFile(file2, pdfjsLib, containingFolder, grandtotal, editor));
              }
            }
          }));
          yield Promise.all(promises);
          this.sort(grandtotal);
          editor.replaceSelection(this.format(grandtotal));
        })
      });
    });
  }
  loadSettings() {
    this.settings = new PDFAnnotationPluginSetting();
    (() => __async(this, null, function* () {
      const loadedSettings = yield this.loadData();
      if (loadedSettings) {
        this.settings.useFolderNames = loadedSettings.useFolderNames;
        this.settings.sortByTopic = loadedSettings.sortByTopic;
      }
    }))();
  }
  onunload() {
  }
  saveHighlightsToFile(filePath, mdString) {
    return __async(this, null, function* () {
      const fileExists = yield this.app.vault.adapter.exists(filePath);
      if (fileExists) {
        yield this.appendHighlightsToFile(filePath, mdString);
      } else {
        yield this.app.vault.create(filePath, mdString);
      }
    });
  }
  appendHighlightsToFile(filePath, note2) {
    return __async(this, null, function* () {
      let existingContent = yield this.app.vault.adapter.read(filePath);
      if (existingContent.length > 0) {
        existingContent = existingContent + "\r\r";
      }
      yield this.app.vault.adapter.write(filePath, existingContent + note2);
    });
  }
};
var PDFAnnotationPluginSetting = class {
  constructor() {
    this.useFolderNames = true;
    this.sortByTopic = true;
  }
};
var PDFAnnotationPluginSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Use Folder Name").setDesc("If enabled, uses the PDF's folder name (instead of the PDF-Filename) for sorting").addToggle((toggle) => toggle.setValue(this.plugin.settings.useFolderNames).onChange((value) => {
      this.plugin.settings.useFolderNames = value;
      this.plugin.saveData(this.plugin.settings);
    }));
    new import_obsidian.Setting(containerEl).setName("Sort by Topic").setDesc("If enabled, uses the notes first line as Topic for primary sorting").addToggle((toggle) => toggle.setValue(this.plugin.settings.sortByTopic).onChange((value) => {
      this.plugin.settings.sortByTopic = value;
      this.plugin.saveData(this.plugin.settings);
    }));
  }
};
